apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: infracontrol-dev
data:
  NODE_ENV: "development"
  MONGODB_URI: "mongodb://mongodb:27017/infracontrol"
  CORS_ORIGIN: "http://frontend:3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: infracontrol-dev
type: Opaque
data:
  JWT_SECRET: "ZGV2X3NlY3JldF9rZXk=" # dev_secret_key in base64
  JWT_EXPIRES_IN: "MWQ=" # 1d in base64
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: infracontrol-dev
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: infracontrol-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: infracontrol-backend:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi" 